---
name: Build Container
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  push-image:
    name: Build and push container image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version: 
          - 38
          - 39
          - 40
        include:
          - version: 39
            support: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        uses: JasonN3/build-action@action
        with:
          image_name: isogenerator
          image_variant: main
          version: ${{ matrix.version }}
          support: ${{ matrix.support }}
          signing_key: ${{ secrets.SIGNING_SECRET }}
        continue-on-error: false
