name: Test Generate ISO

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

env:
  ARCH: ${{ inputs.ARCH || 'x86_64' }}
  IMAGE_NAME: ${{ inputs.IMAGE_NAME || 'base-main' }}
  IMAGE_REPO: ${{ inputs.IMAGE_REPO || 'ghcr.io/ublue-os' }}
  IMAGE_TAG: ${{ inputs.IMAGE_TAG || 'latest' }}
  VARIANT: ${{ inputs.VARIANT || 'Kinoite' }}
  VERSION: ${{ inputs.VERSION || '39' }}
  WEB_UI: ${{ inputs.WEB_UI || 'false' }}
  CURR_REPO: ${{ inputs.BUILD_REPO || github.repository }}
  CURR_REF: ${{ inputs.BUILD_REF || github.ref }}

jobs:
  build-and-push-iso:
    runs-on: ubuntu-latest
    container:
      image: fedora:39
      options: "--privileged"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build ISO
        uses: ublue-os/isogenerator
        with:
          ARCH: 'x86_64'
          IMAGE_NAME: 'base-main'
          IMAGE_REPO: 'ghcr.io/ublue-os'
          IMAGE_TAG: 'latest'
          VARIANT: 'Kinoite'
          VERSION: '39'
          WEB_UI: 'false'
          CURR_REPO: ${{ github.repository }}
          CURR_REF: ${{ github.ref }}
