name: Test Generate ISO

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - 'Containerfile'
      - '*.md'
      - 'LICENSE'
      - 'CODEOWNERS'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Containerfile'
      - '*.md'
      - 'LICENSE'
      - 'CODEOWNERS'

jobs:
  build-and-push-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    container:
      image: fedora:39
      options: "--privileged"
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version: 
          - 38
          - 39
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        uses: ./
        with:
          ARCH: 'x86_64'
          IMAGE_NAME: 'base-main'
          IMAGE_REPO: 'ghcr.io/ublue-os'
          IMAGE_TAG: 'latest'
          VARIANT: 'Kinoite'
          VERSION: ${{ matrix.version }}
          ACTION_REPO: ${{ github.repository }}
          ACTION_REF: ${{ github.ref }}
