name: Test Generate ISO

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Containerfile'
      - '*.md'
      - 'LICENSE'
      - 'CODEOWNERS'

jobs:
  build-and-push-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    container:
      image: fedora:39
      options: "--privileged"
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        version: 
          - 38
          - 39
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        uses: ./
        with:
          ARCH: 'x86_64'
          IMAGE_NAME: 'base-main'
          IMAGE_REPO: 'ghcr.io/ublue-os'
          VARIANT: 'Kinoite'
          VERSION: 39
          ACTION_REPO: ${{ github.repository }}
          ACTION_REF: ${{ github.ref }}

  check:
    name: Check build successful
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs:
      - build-and-push-iso
    steps:
      - name: Exit on failure for main
        if: ${{ needs.build-and-push-iso.result == 'failure' || needs.build-and-push-iso.result == 'skipped' }}
        shell: bash
        run: exit 1
      - name: Exit
        shell: bash
        run: exit 0