name: Test Generate ISO

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - 'Containerfile'
      - '*.md'
      - 'LICENSE'
      - 'CODEOWNERS'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'Containerfile'
      - '*.md'
      - 'LICENSE'
      - 'CODEOWNERS'

jobs:
  build-and-push-iso:
    runs-on: ubuntu-latest
    container:
      image: fedora:39
      options: "--privileged"
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build ISO
        uses: ublue-os/isogenerator
        with:
          ARCH: 'x86_64'
          IMAGE_NAME: 'base-main'
          IMAGE_REPO: 'ghcr.io/ublue-os'
          IMAGE_TAG: 'latest'
          VARIANT: 'Kinoite'
          VERSION: '39'
          WEB_UI: 'false'
          ACTION_REPO: ${{ github.repository }}
          ACTION_REF: ${{ github.ref }}
